### ISSUE TITLE
[Feature request]: Certificate-based authentication

### ISSUE THREAD

**Issue by BatisteDONDOGLIO** [ugurkocde/IntuneAssignmentChecker#10]
First, I would like to express my gratitude for this awesome script!

Now, it would be nice to have more options when it comes to authenticating the app, and mainly through a certificate. 

Currently, the app only supports the use of client secrets as a means to retrieving an Azure auth token. 
While this is rather simple and works fine, certificate-based authentication might be desired instead, in order to increase security. 

I'm sure this feature could be useful to others as well.

Thanking you in advance!

**Comment by ugurkocde** [comment]
Hi @BatisteDONDOGLIO, have a look in v2. I have added the certificate method via thumbprint. You can alternitively use a certname.

**Comment by BatisteDONDOGLIO** [comment]
Hi @ugurkocde, amazing work, thank you!

I will check it out and run a few tests when I have some time, and report here.

Have a nice day!
