### ISSUE TITLE
Permissions "Test" Should also factor in ReadWrite

### ISSUE THREAD

**Issue by jamesvincent** [ugurkocde/IntuneAssignmentChecker#18]
Permissions "Test" should also factor in ReadWrite permissions.

The script is checking specifically for "Read" permissions, but users with ReadWrite permissions would also pass the required permission test. I have had two colleagues reach out to me saying the script is failing permission checks, but in reality, because they have ReadWrite, it's fine -- the script is just complaining.

**Comment by ugurkocde** [comment]
Very good and valid point. Thanks @jamesvincent
