### ISSUE TITLE
Script doesn't include the all users / all device group

### ISSUE THREAD

**Issue by Stanzoheetik** [ugurkocde/IntuneAssignmentChecker#2]
Many thanks for your efforts! 

It looks like the script is not showing the 'all devices' and 'all users' group.

When you search a device, applications that are assigned to the 'all devices' group are not showed in the apps overview

**Comment by ugurkocde** [comment]
Hi @Stanzoheetik,

thanks for the info. I have released a new Version of the script that handles your Issue and a lot more. Please have a look. 

Closing the Issue for now.
