### ISSUE TITLE
Error: "WARNING: The following permissions are missing"

### ISSUE THREAD

**Issue by KrpaKrpa** [ugurkocde/IntuneAssignmentChecker#26]
Maybe I am doing a rookie mistake but I would appreciate help on this matter. I created the app registration, added the cert, added the required data in the ps script (app id, tenantid, certThumbprint etc..) as well as added the permissions.

![image](https://github.com/user-attachments/assets/bd541b4c-d8a5-4053-bb18-6b92c9578c5d)

But I get this error?

![image](https://github.com/user-attachments/assets/8352368e-8808-47ac-bf13-dac5cb5bffdb)

and

![image](https://github.com/user-attachments/assets/7490db46-a396-43f9-8ff3-247c05f51be4)

What am I missing?

Thank you in advance

**Comment by ugurkocde** [comment]
Hi @KrpaKrpa,

thats not a rookie mistake. I have not really documented that well enough.

The permissions have to be "Application" and not "Delegated". You also have to grant admin consent for each permission.

Can you test it out and give feedback please?

FYI: I am currently documenting that part and will update the readme accordingly.

Best
Ugur

**Comment by ugurkocde** [comment]
The updated readme should do a better job on guiding you on the necessary steps. Closing the Issue for now until there is any feedback.
