### ISSUE TITLE
Feature Request: Add Support for Proactive Remediation scripts 

### ISSUE THREAD

**Issue by ugurkocde** [ugurkocde/IntuneAssignmentChecker#37]
https://graph.microsoft.com/beta/deviceManagement/deviceHealthScripts

**Comment by royklo** [comment]
@ugurkocde maybe something I can help you out with? It will almost be the same function as the platform scripts with a few little differences here en there. 

If you could give me access to the 2.6 with the platform script I could continue on your platform script function.

**Comment by ugurkocde** [comment]
Finished and shipped with 2.6.0. Thanks for the Feature Request :)
