### ISSUE TITLE
App Protection & App Configuration Policies

### ISSUE THREAD

**Issue by cjberg48** [ugurkocde/IntuneAssignmentChecker#8]
Love this script! We were trying to come up with something and found this and it has saved us so much time!

I would love to see what App Protection & App Configuration Policies are applied to groups/users/devices. We are in the middle of trying to consolidate our policies/profiles and this would be a huge benefit to see.

**Comment by ugurkocde** [comment]
Thanks @cjberg48. I will be adding this to the next version. No ATA as of now.

**Comment by cjberg48** [comment]
Thank you!

**Comment by ugurkocde** [comment]
Hey @cjberg48 , this is now included in v2. Please have a look.

**Comment by cjberg48** [comment]
Awesome, thank you very much!
