### ISSUE TITLE
Only seems to return a subset of config policies.

### ISSUE THREAD

**Issue by jim-watts** [ugurkocde/IntuneAssignmentChecker#9]
Only seems to return a subset of config policies.

"Device Restrictions", "defender for endpoint" and "custom" type config policies are returned, but not "settings catalog" or "admin template" type config policies

It looks like the "https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations" call just doesn't return them?

I'm using option5, as I'm looking at AllDevice policies but I imagine its the same for all options.

Anybody else seeing this?

**Comment by ugurkocde** [comment]
Can you try the other options and see if there are the same behavior. It should show all the settings you mentioned.

**Comment by ugurkocde** [comment]
ping @jim-watts
